name: Docker Build

on:
  workflow_call:
    inputs:

      context:
        description: "Docker context path"
        default: .
        type: string

      timeout:
        description: "Timeout for jobs in minutes"
        default: 15
        type: number

      qemu_platforms:
        description: "Comma-separated list of platforms to include for Docker images"
        default: ""
        type: string

      docker_platforms:
        description: "Comma-separated list of platforms to include for Docker images"
        default: "linux/amd64"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: ${{ inputs.timeout }}
    steps:
    - uses: 'actions/checkout@v3'

    - name: Set up QEMU
      if: inputs.platforms != ''
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.qemu_platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ inputs.docker_platforms }}
        context: ${{ inputs.context }}

        cache-from: type=gha
        cache-to: type=gha,mode=max

        push: false
