name: Nix

on:
  workflow_call:
    inputs:

      timeout:
        description: "Timeout for jobs in minutes"
        default: 15
        type: number

      script:
        description: "run with script in Nix"
        default: "true"
        type: string

jobs:

  nix:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: workflow/nix-shell-action@v3
      with:
        script: ${{ inputs.script }}
