name: Nix

on:
  workflow_call:
    inputs:

      timeout:
        description: "Timeout for jobs in minutes"
        default: 15
        type: number

      script:
        description: "run with script in Nix"
        default: "true"
        type: string

      flakes-from-devshell:
        description: "Use devshell flake setup"
        default: false
        type: boolean

jobs:

  nix:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: workflow/nix-shell-action@v3.3.2
      with:
        flakes-from-devshell: ${{ inputs.flakes-from-devshell }}
        script: ${{ inputs.script }}
