name: Rust Test

on:
  workflow_call:
    inputs:

      timeout:
        description: "Timeout for jobs in minutes"
        default: 15
        type: number

      setup_script:
        description: ""
        default: ""
        type: string

      working-directory:
        description: "Working directory for jobs"
        default: "."
        type: string


jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
    - uses: actions/checkout@v5

    - name: Setup Script
      if: ${{ inputs.setup_script }}
      run: ${{ inputs.setup_script }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose
      env:
        SQLX_OFFLINE: true

    - name: Run tests
      run: cargo test --verbose
      env:
        SQLX_OFFLINE: true
